# Generated by Django 4.0.3 on 2022-04-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_note_noteform_task_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteForm',
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
